### ISSUE TITLE
Change project language (Which is shown on Github)

### ISSUE THREAD

**Issue by ofarukcaki** [OFarukCaki/Bitcoin101App-Xamarin.Forms#1]
Project shown as written in 'Java' on Github, but it is a C# project actually. Need to be C# project by igroring java files.

**Comment by V1shvesh** [comment]
Can I??

**Comment by ofarukcaki** [comment]
Of course

**Comment by V1shvesh** [comment]
I gotta make changes in .gitignore right??

**Comment by ofarukcaki** [comment]
I guess so

**Comment by V1shvesh** [comment]
Can you tell me which folder contains the majority of Java code in your repo?

**Comment by V1shvesh** [comment]
I think this'll work:
https://medium.com/black-tech-diva/how-to-change-repo-language-in-github-c3e07819c5bb

**Comment by bitspill** [comment]
Fixed by #2 and #3
